// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/pokt/query.proto

package server

import (
	types "github.com/lostak/pokt/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgGetPortfolio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MsgGetPortfolio) Reset() {
	*x = MsgGetPortfolio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokt_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetPortfolio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetPortfolio) ProtoMessage() {}

func (x *MsgGetPortfolio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokt_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetPortfolio.ProtoReflect.Descriptor instead.
func (*MsgGetPortfolio) Descriptor() ([]byte, []int) {
	return file_proto_pokt_query_proto_rawDescGZIP(), []int{0}
}

func (x *MsgGetPortfolio) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MsgGetPortfolioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Portfolio *types.Portfolio `protobuf:"bytes,1,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
}

func (x *MsgGetPortfolioResponse) Reset() {
	*x = MsgGetPortfolioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokt_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetPortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetPortfolioResponse) ProtoMessage() {}

func (x *MsgGetPortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokt_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetPortfolioResponse.ProtoReflect.Descriptor instead.
func (*MsgGetPortfolioResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokt_query_proto_rawDescGZIP(), []int{1}
}

func (x *MsgGetPortfolioResponse) GetPortfolio() *types.Portfolio {
	if x != nil {
		return x.Portfolio
	}
	return nil
}

type MsgGetAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Portfolio string `protobuf:"bytes,2,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
}

func (x *MsgGetAccount) Reset() {
	*x = MsgGetAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokt_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetAccount) ProtoMessage() {}

func (x *MsgGetAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokt_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetAccount.ProtoReflect.Descriptor instead.
func (*MsgGetAccount) Descriptor() ([]byte, []int) {
	return file_proto_pokt_query_proto_rawDescGZIP(), []int{2}
}

func (x *MsgGetAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgGetAccount) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

type MsgGetAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *types.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *MsgGetAccountResponse) Reset() {
	*x = MsgGetAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokt_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetAccountResponse) ProtoMessage() {}

func (x *MsgGetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokt_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetAccountResponse.ProtoReflect.Descriptor instead.
func (*MsgGetAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokt_query_proto_rawDescGZIP(), []int{3}
}

func (x *MsgGetAccountResponse) GetAccount() *types.Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type MsgGetChain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Account   string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Portfolio string `protobuf:"bytes,3,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
}

func (x *MsgGetChain) Reset() {
	*x = MsgGetChain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokt_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetChain) ProtoMessage() {}

func (x *MsgGetChain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokt_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetChain.ProtoReflect.Descriptor instead.
func (*MsgGetChain) Descriptor() ([]byte, []int) {
	return file_proto_pokt_query_proto_rawDescGZIP(), []int{4}
}

func (x *MsgGetChain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgGetChain) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MsgGetChain) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

type MsgGetChainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain *types.Chain `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
}

func (x *MsgGetChainResponse) Reset() {
	*x = MsgGetChainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokt_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetChainResponse) ProtoMessage() {}

func (x *MsgGetChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokt_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetChainResponse.ProtoReflect.Descriptor instead.
func (*MsgGetChainResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokt_query_proto_rawDescGZIP(), []int{5}
}

func (x *MsgGetChainResponse) GetChain() *types.Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

type MsgGetToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chain     string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Account   string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Portfolio string `protobuf:"bytes,4,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
}

func (x *MsgGetToken) Reset() {
	*x = MsgGetToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokt_query_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetToken) ProtoMessage() {}

func (x *MsgGetToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokt_query_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetToken.ProtoReflect.Descriptor instead.
func (*MsgGetToken) Descriptor() ([]byte, []int) {
	return file_proto_pokt_query_proto_rawDescGZIP(), []int{6}
}

func (x *MsgGetToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgGetToken) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *MsgGetToken) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MsgGetToken) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

type MsgGetTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *types.Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *MsgGetTokenResponse) Reset() {
	*x = MsgGetTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokt_query_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetTokenResponse) ProtoMessage() {}

func (x *MsgGetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokt_query_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetTokenResponse.ProtoReflect.Descriptor instead.
func (*MsgGetTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokt_query_proto_rawDescGZIP(), []int{7}
}

func (x *MsgGetTokenResponse) GetToken() *types.Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type MsgGetAmounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chain     string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Account   string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Portfolio string `protobuf:"bytes,4,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
}

func (x *MsgGetAmounts) Reset() {
	*x = MsgGetAmounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokt_query_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetAmounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetAmounts) ProtoMessage() {}

func (x *MsgGetAmounts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokt_query_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetAmounts.ProtoReflect.Descriptor instead.
func (*MsgGetAmounts) Descriptor() ([]byte, []int) {
	return file_proto_pokt_query_proto_rawDescGZIP(), []int{8}
}

func (x *MsgGetAmounts) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgGetAmounts) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *MsgGetAmounts) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MsgGetAmounts) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

type MsgGetAmountsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amounts []*types.AmountEntry `protobuf:"bytes,1,rep,name=amounts,proto3" json:"amounts,omitempty"`
}

func (x *MsgGetAmountsResponse) Reset() {
	*x = MsgGetAmountsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokt_query_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetAmountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetAmountsResponse) ProtoMessage() {}

func (x *MsgGetAmountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokt_query_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetAmountsResponse.ProtoReflect.Descriptor instead.
func (*MsgGetAmountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokt_query_proto_rawDescGZIP(), []int{9}
}

func (x *MsgGetAmountsResponse) GetAmounts() []*types.AmountEntry {
	if x != nil {
		return x.Amounts
	}
	return nil
}

var File_proto_pokt_query_proto protoreflect.FileDescriptor

var file_proto_pokt_query_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x74, 0x2f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b,
	0x74, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x25, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x66,
	0x6f, 0x6c, 0x69, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4e, 0x0a, 0x17, 0x4d, 0x73, 0x67, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x09, 0x70,
	0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x22, 0x41, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x22, 0x46, 0x0a, 0x15, 0x4d,
	0x73, 0x67, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x59, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x22, 0x3e,
	0x0a, 0x13, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x22, 0x6f,
	0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x22,
	0x3e, 0x0a, 0x13, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x71, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c,
	0x69, 0x6f, 0x22, 0x4a, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70,
	0x6f, 0x6b, 0x74, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x32, 0x87,
	0x03, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x52, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x12, 0x1c, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x72,
	0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x1a, 0x24, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x66,
	0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x6f, 0x6b,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x1a, 0x20, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d,
	0x73, 0x67, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18,
	0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x20, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x1a, 0x22, 0x2e, 0x70, 0x6f, 0x6b, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6f, 0x73, 0x74, 0x61, 0x6b, 0x2f, 0x70, 0x6f,
	0x6b, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_pokt_query_proto_rawDescOnce sync.Once
	file_proto_pokt_query_proto_rawDescData = file_proto_pokt_query_proto_rawDesc
)

func file_proto_pokt_query_proto_rawDescGZIP() []byte {
	file_proto_pokt_query_proto_rawDescOnce.Do(func() {
		file_proto_pokt_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pokt_query_proto_rawDescData)
	})
	return file_proto_pokt_query_proto_rawDescData
}

var file_proto_pokt_query_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_pokt_query_proto_goTypes = []interface{}{
	(*MsgGetPortfolio)(nil),         // 0: pokt.server.MsgGetPortfolio
	(*MsgGetPortfolioResponse)(nil), // 1: pokt.server.MsgGetPortfolioResponse
	(*MsgGetAccount)(nil),           // 2: pokt.server.MsgGetAccount
	(*MsgGetAccountResponse)(nil),   // 3: pokt.server.MsgGetAccountResponse
	(*MsgGetChain)(nil),             // 4: pokt.server.MsgGetChain
	(*MsgGetChainResponse)(nil),     // 5: pokt.server.MsgGetChainResponse
	(*MsgGetToken)(nil),             // 6: pokt.server.MsgGetToken
	(*MsgGetTokenResponse)(nil),     // 7: pokt.server.MsgGetTokenResponse
	(*MsgGetAmounts)(nil),           // 8: pokt.server.MsgGetAmounts
	(*MsgGetAmountsResponse)(nil),   // 9: pokt.server.MsgGetAmountsResponse
	(*types.Portfolio)(nil),         // 10: pokt.types.Portfolio
	(*types.Account)(nil),           // 11: pokt.types.Account
	(*types.Chain)(nil),             // 12: pokt.types.Chain
	(*types.Token)(nil),             // 13: pokt.types.Token
	(*types.AmountEntry)(nil),       // 14: pokt.types.AmountEntry
}
var file_proto_pokt_query_proto_depIdxs = []int32{
	10, // 0: pokt.server.MsgGetPortfolioResponse.portfolio:type_name -> pokt.types.Portfolio
	11, // 1: pokt.server.MsgGetAccountResponse.account:type_name -> pokt.types.Account
	12, // 2: pokt.server.MsgGetChainResponse.chain:type_name -> pokt.types.Chain
	13, // 3: pokt.server.MsgGetTokenResponse.token:type_name -> pokt.types.Token
	14, // 4: pokt.server.MsgGetAmountsResponse.amounts:type_name -> pokt.types.AmountEntry
	0,  // 5: pokt.server.Query.GetPortfolio:input_type -> pokt.server.MsgGetPortfolio
	2,  // 6: pokt.server.Query.GetAccount:input_type -> pokt.server.MsgGetAccount
	4,  // 7: pokt.server.Query.GetChain:input_type -> pokt.server.MsgGetChain
	6,  // 8: pokt.server.Query.GetToken:input_type -> pokt.server.MsgGetToken
	8,  // 9: pokt.server.Query.GetAmounts:input_type -> pokt.server.MsgGetAmounts
	1,  // 10: pokt.server.Query.GetPortfolio:output_type -> pokt.server.MsgGetPortfolioResponse
	3,  // 11: pokt.server.Query.GetAccount:output_type -> pokt.server.MsgGetAccountResponse
	5,  // 12: pokt.server.Query.GetChain:output_type -> pokt.server.MsgGetChainResponse
	7,  // 13: pokt.server.Query.GetToken:output_type -> pokt.server.MsgGetTokenResponse
	9,  // 14: pokt.server.Query.GetAmounts:output_type -> pokt.server.MsgGetAmountsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_pokt_query_proto_init() }
func file_proto_pokt_query_proto_init() {
	if File_proto_pokt_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pokt_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetPortfolio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokt_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetPortfolioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokt_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokt_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokt_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetChain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokt_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetChainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokt_query_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokt_query_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokt_query_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetAmounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokt_query_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetAmountsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pokt_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pokt_query_proto_goTypes,
		DependencyIndexes: file_proto_pokt_query_proto_depIdxs,
		MessageInfos:      file_proto_pokt_query_proto_msgTypes,
	}.Build()
	File_proto_pokt_query_proto = out.File
	file_proto_pokt_query_proto_rawDesc = nil
	file_proto_pokt_query_proto_goTypes = nil
	file_proto_pokt_query_proto_depIdxs = nil
}
