// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/pokt/query.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	GetPortfolio(ctx context.Context, in *MsgGetPortfolio, opts ...grpc.CallOption) (*MsgGetPortfolioResponse, error)
	// rpc GetAccounts(MsgGetAccounts) returns (stream MsgGetAccountsResponse);
	GetAccount(ctx context.Context, in *MsgGetAccount, opts ...grpc.CallOption) (*MsgGetAccountResponse, error)
	// rpc GetChains(MsgGetChains) returns (stream MsgGetChainsResponse)
	GetChain(ctx context.Context, in *MsgGetChain, opts ...grpc.CallOption) (*MsgGetChainResponse, error)
	// rpc GetTokens(MsgGetTokens) returns (stream MsgGetTokensResponse)
	GetToken(ctx context.Context, in *MsgGetToken, opts ...grpc.CallOption) (*MsgGetTokenResponse, error)
	GetAmounts(ctx context.Context, in *MsgGetAmounts, opts ...grpc.CallOption) (*MsgGetAmountsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetPortfolio(ctx context.Context, in *MsgGetPortfolio, opts ...grpc.CallOption) (*MsgGetPortfolioResponse, error) {
	out := new(MsgGetPortfolioResponse)
	err := c.cc.Invoke(ctx, "/pokt.server.Query/GetPortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAccount(ctx context.Context, in *MsgGetAccount, opts ...grpc.CallOption) (*MsgGetAccountResponse, error) {
	out := new(MsgGetAccountResponse)
	err := c.cc.Invoke(ctx, "/pokt.server.Query/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetChain(ctx context.Context, in *MsgGetChain, opts ...grpc.CallOption) (*MsgGetChainResponse, error) {
	out := new(MsgGetChainResponse)
	err := c.cc.Invoke(ctx, "/pokt.server.Query/GetChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetToken(ctx context.Context, in *MsgGetToken, opts ...grpc.CallOption) (*MsgGetTokenResponse, error) {
	out := new(MsgGetTokenResponse)
	err := c.cc.Invoke(ctx, "/pokt.server.Query/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAmounts(ctx context.Context, in *MsgGetAmounts, opts ...grpc.CallOption) (*MsgGetAmountsResponse, error) {
	out := new(MsgGetAmountsResponse)
	err := c.cc.Invoke(ctx, "/pokt.server.Query/GetAmounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	GetPortfolio(context.Context, *MsgGetPortfolio) (*MsgGetPortfolioResponse, error)
	// rpc GetAccounts(MsgGetAccounts) returns (stream MsgGetAccountsResponse);
	GetAccount(context.Context, *MsgGetAccount) (*MsgGetAccountResponse, error)
	// rpc GetChains(MsgGetChains) returns (stream MsgGetChainsResponse)
	GetChain(context.Context, *MsgGetChain) (*MsgGetChainResponse, error)
	// rpc GetTokens(MsgGetTokens) returns (stream MsgGetTokensResponse)
	GetToken(context.Context, *MsgGetToken) (*MsgGetTokenResponse, error)
	GetAmounts(context.Context, *MsgGetAmounts) (*MsgGetAmountsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) GetPortfolio(context.Context, *MsgGetPortfolio) (*MsgGetPortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolio not implemented")
}
func (UnimplementedQueryServer) GetAccount(context.Context, *MsgGetAccount) (*MsgGetAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedQueryServer) GetChain(context.Context, *MsgGetChain) (*MsgGetChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChain not implemented")
}
func (UnimplementedQueryServer) GetToken(context.Context, *MsgGetToken) (*MsgGetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedQueryServer) GetAmounts(context.Context, *MsgGetAmounts) (*MsgGetAmountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAmounts not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_GetPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGetPortfolio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.server.Query/GetPortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPortfolio(ctx, req.(*MsgGetPortfolio))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGetAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.server.Query/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAccount(ctx, req.(*MsgGetAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGetChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.server.Query/GetChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetChain(ctx, req.(*MsgGetChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGetToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.server.Query/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetToken(ctx, req.(*MsgGetToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAmounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGetAmounts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAmounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.server.Query/GetAmounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAmounts(ctx, req.(*MsgGetAmounts))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pokt.server.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPortfolio",
			Handler:    _Query_GetPortfolio_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _Query_GetAccount_Handler,
		},
		{
			MethodName: "GetChain",
			Handler:    _Query_GetChain_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _Query_GetToken_Handler,
		},
		{
			MethodName: "GetAmounts",
			Handler:    _Query_GetAmounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pokt/query.proto",
}
