// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/pokt/tx.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MsgServiceClient is the client API for MsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgServiceClient interface {
	CreatePortfolio(ctx context.Context, in *MsgCreatePortfolio, opts ...grpc.CallOption) (*MsgCreatePortfolioResponse, error)
	CreateAccount(ctx context.Context, in *MsgCreateAccount, opts ...grpc.CallOption) (*MsgCreateAccountResponse, error)
	CreateChain(ctx context.Context, in *MsgCreateChain, opts ...grpc.CallOption) (*MsgCreateChainResponse, error)
	CreateToken(ctx context.Context, in *MsgCreateToken, opts ...grpc.CallOption) (*MsgCreateTokenResponse, error)
	CreateAmount(ctx context.Context, in *MsgCreateAmount, opts ...grpc.CallOption) (*MsgCreateAmountResponse, error)
	UpdatePortfolioName(ctx context.Context, in *MsgUpdatePortfolioName, opts ...grpc.CallOption) (*MsgUpdatePortfolioNameResponse, error)
	UpdateAccountName(ctx context.Context, in *MsgUpdateAccountName, opts ...grpc.CallOption) (*MsgUpdateAccountNameResponse, error)
	UpdateChainName(ctx context.Context, in *MsgUpdateChainName, opts ...grpc.CallOption) (*MsgUpdateChainNameResponse, error)
	UpdateTokenName(ctx context.Context, in *MsgUpdateTokenName, opts ...grpc.CallOption) (*MsgUpdateTokenNameResponse, error)
	UpdateCoinGeckoId(ctx context.Context, in *MsgUpdateCoinGeckoId, opts ...grpc.CallOption) (*MsgUpdateCoinGeckoIdResponse, error)
	UpdateAddress(ctx context.Context, in *MsgUpdateAddress, opts ...grpc.CallOption) (*MsgUpdateAddressResponse, error)
	ClearPortfolio(ctx context.Context, in *MsgClearPortfolio, opts ...grpc.CallOption) (*MsgClearPortfolioResponse, error)
	ClearAccount(ctx context.Context, in *MsgClearAccount, opts ...grpc.CallOption) (*MsgClearAccountResponse, error)
	ClearChain(ctx context.Context, in *MsgClearChain, opts ...grpc.CallOption) (*MsgClearChainResponse, error)
	ClearToken(ctx context.Context, in *MsgClearToken, opts ...grpc.CallOption) (*MsgClearTokenResponse, error)
	DeletePortfolio(ctx context.Context, in *MsgDeletePortfolio, opts ...grpc.CallOption) (*MsgDeletePortfolioResponse, error)
	DeleteAccount(ctx context.Context, in *MsgDeleteAccount, opts ...grpc.CallOption) (*MsgDeleteAccountResponse, error)
	DeleteChain(ctx context.Context, in *MsgDeleteChain, opts ...grpc.CallOption) (*MsgDeleteChainResponse, error)
	DeleteToken(ctx context.Context, in *MsgDeleteToken, opts ...grpc.CallOption) (*MsgDeleteTokenResponse, error)
	DeleteLastAmount(ctx context.Context, in *MsgDeleteLastAmount, opts ...grpc.CallOption) (*MsgDeleteLastAmountResponse, error)
}

type msgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgServiceClient(cc grpc.ClientConnInterface) MsgServiceClient {
	return &msgServiceClient{cc}
}

func (c *msgServiceClient) CreatePortfolio(ctx context.Context, in *MsgCreatePortfolio, opts ...grpc.CallOption) (*MsgCreatePortfolioResponse, error) {
	out := new(MsgCreatePortfolioResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/CreatePortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateAccount(ctx context.Context, in *MsgCreateAccount, opts ...grpc.CallOption) (*MsgCreateAccountResponse, error) {
	out := new(MsgCreateAccountResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateChain(ctx context.Context, in *MsgCreateChain, opts ...grpc.CallOption) (*MsgCreateChainResponse, error) {
	out := new(MsgCreateChainResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/CreateChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateToken(ctx context.Context, in *MsgCreateToken, opts ...grpc.CallOption) (*MsgCreateTokenResponse, error) {
	out := new(MsgCreateTokenResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/CreateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateAmount(ctx context.Context, in *MsgCreateAmount, opts ...grpc.CallOption) (*MsgCreateAmountResponse, error) {
	out := new(MsgCreateAmountResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/CreateAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) UpdatePortfolioName(ctx context.Context, in *MsgUpdatePortfolioName, opts ...grpc.CallOption) (*MsgUpdatePortfolioNameResponse, error) {
	out := new(MsgUpdatePortfolioNameResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/UpdatePortfolioName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) UpdateAccountName(ctx context.Context, in *MsgUpdateAccountName, opts ...grpc.CallOption) (*MsgUpdateAccountNameResponse, error) {
	out := new(MsgUpdateAccountNameResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/UpdateAccountName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) UpdateChainName(ctx context.Context, in *MsgUpdateChainName, opts ...grpc.CallOption) (*MsgUpdateChainNameResponse, error) {
	out := new(MsgUpdateChainNameResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/UpdateChainName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) UpdateTokenName(ctx context.Context, in *MsgUpdateTokenName, opts ...grpc.CallOption) (*MsgUpdateTokenNameResponse, error) {
	out := new(MsgUpdateTokenNameResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/UpdateTokenName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) UpdateCoinGeckoId(ctx context.Context, in *MsgUpdateCoinGeckoId, opts ...grpc.CallOption) (*MsgUpdateCoinGeckoIdResponse, error) {
	out := new(MsgUpdateCoinGeckoIdResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/UpdateCoinGeckoId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) UpdateAddress(ctx context.Context, in *MsgUpdateAddress, opts ...grpc.CallOption) (*MsgUpdateAddressResponse, error) {
	out := new(MsgUpdateAddressResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/UpdateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ClearPortfolio(ctx context.Context, in *MsgClearPortfolio, opts ...grpc.CallOption) (*MsgClearPortfolioResponse, error) {
	out := new(MsgClearPortfolioResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/ClearPortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ClearAccount(ctx context.Context, in *MsgClearAccount, opts ...grpc.CallOption) (*MsgClearAccountResponse, error) {
	out := new(MsgClearAccountResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/ClearAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ClearChain(ctx context.Context, in *MsgClearChain, opts ...grpc.CallOption) (*MsgClearChainResponse, error) {
	out := new(MsgClearChainResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/ClearChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ClearToken(ctx context.Context, in *MsgClearToken, opts ...grpc.CallOption) (*MsgClearTokenResponse, error) {
	out := new(MsgClearTokenResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/ClearToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) DeletePortfolio(ctx context.Context, in *MsgDeletePortfolio, opts ...grpc.CallOption) (*MsgDeletePortfolioResponse, error) {
	out := new(MsgDeletePortfolioResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/DeletePortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) DeleteAccount(ctx context.Context, in *MsgDeleteAccount, opts ...grpc.CallOption) (*MsgDeleteAccountResponse, error) {
	out := new(MsgDeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/DeleteAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) DeleteChain(ctx context.Context, in *MsgDeleteChain, opts ...grpc.CallOption) (*MsgDeleteChainResponse, error) {
	out := new(MsgDeleteChainResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/DeleteChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) DeleteToken(ctx context.Context, in *MsgDeleteToken, opts ...grpc.CallOption) (*MsgDeleteTokenResponse, error) {
	out := new(MsgDeleteTokenResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/DeleteToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) DeleteLastAmount(ctx context.Context, in *MsgDeleteLastAmount, opts ...grpc.CallOption) (*MsgDeleteLastAmountResponse, error) {
	out := new(MsgDeleteLastAmountResponse)
	err := c.cc.Invoke(ctx, "/pokt.keeper.MsgService/DeleteLastAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServiceServer is the server API for MsgService service.
// All implementations must embed UnimplementedMsgServiceServer
// for forward compatibility
type MsgServiceServer interface {
	CreatePortfolio(context.Context, *MsgCreatePortfolio) (*MsgCreatePortfolioResponse, error)
	CreateAccount(context.Context, *MsgCreateAccount) (*MsgCreateAccountResponse, error)
	CreateChain(context.Context, *MsgCreateChain) (*MsgCreateChainResponse, error)
	CreateToken(context.Context, *MsgCreateToken) (*MsgCreateTokenResponse, error)
	CreateAmount(context.Context, *MsgCreateAmount) (*MsgCreateAmountResponse, error)
	UpdatePortfolioName(context.Context, *MsgUpdatePortfolioName) (*MsgUpdatePortfolioNameResponse, error)
	UpdateAccountName(context.Context, *MsgUpdateAccountName) (*MsgUpdateAccountNameResponse, error)
	UpdateChainName(context.Context, *MsgUpdateChainName) (*MsgUpdateChainNameResponse, error)
	UpdateTokenName(context.Context, *MsgUpdateTokenName) (*MsgUpdateTokenNameResponse, error)
	UpdateCoinGeckoId(context.Context, *MsgUpdateCoinGeckoId) (*MsgUpdateCoinGeckoIdResponse, error)
	UpdateAddress(context.Context, *MsgUpdateAddress) (*MsgUpdateAddressResponse, error)
	ClearPortfolio(context.Context, *MsgClearPortfolio) (*MsgClearPortfolioResponse, error)
	ClearAccount(context.Context, *MsgClearAccount) (*MsgClearAccountResponse, error)
	ClearChain(context.Context, *MsgClearChain) (*MsgClearChainResponse, error)
	ClearToken(context.Context, *MsgClearToken) (*MsgClearTokenResponse, error)
	DeletePortfolio(context.Context, *MsgDeletePortfolio) (*MsgDeletePortfolioResponse, error)
	DeleteAccount(context.Context, *MsgDeleteAccount) (*MsgDeleteAccountResponse, error)
	DeleteChain(context.Context, *MsgDeleteChain) (*MsgDeleteChainResponse, error)
	DeleteToken(context.Context, *MsgDeleteToken) (*MsgDeleteTokenResponse, error)
	DeleteLastAmount(context.Context, *MsgDeleteLastAmount) (*MsgDeleteLastAmountResponse, error)
	mustEmbedUnimplementedMsgServiceServer()
}

// UnimplementedMsgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServiceServer struct {
}

func (UnimplementedMsgServiceServer) CreatePortfolio(context.Context, *MsgCreatePortfolio) (*MsgCreatePortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePortfolio not implemented")
}
func (UnimplementedMsgServiceServer) CreateAccount(context.Context, *MsgCreateAccount) (*MsgCreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedMsgServiceServer) CreateChain(context.Context, *MsgCreateChain) (*MsgCreateChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChain not implemented")
}
func (UnimplementedMsgServiceServer) CreateToken(context.Context, *MsgCreateToken) (*MsgCreateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToken not implemented")
}
func (UnimplementedMsgServiceServer) CreateAmount(context.Context, *MsgCreateAmount) (*MsgCreateAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAmount not implemented")
}
func (UnimplementedMsgServiceServer) UpdatePortfolioName(context.Context, *MsgUpdatePortfolioName) (*MsgUpdatePortfolioNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePortfolioName not implemented")
}
func (UnimplementedMsgServiceServer) UpdateAccountName(context.Context, *MsgUpdateAccountName) (*MsgUpdateAccountNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccountName not implemented")
}
func (UnimplementedMsgServiceServer) UpdateChainName(context.Context, *MsgUpdateChainName) (*MsgUpdateChainNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChainName not implemented")
}
func (UnimplementedMsgServiceServer) UpdateTokenName(context.Context, *MsgUpdateTokenName) (*MsgUpdateTokenNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTokenName not implemented")
}
func (UnimplementedMsgServiceServer) UpdateCoinGeckoId(context.Context, *MsgUpdateCoinGeckoId) (*MsgUpdateCoinGeckoIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCoinGeckoId not implemented")
}
func (UnimplementedMsgServiceServer) UpdateAddress(context.Context, *MsgUpdateAddress) (*MsgUpdateAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAddress not implemented")
}
func (UnimplementedMsgServiceServer) ClearPortfolio(context.Context, *MsgClearPortfolio) (*MsgClearPortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearPortfolio not implemented")
}
func (UnimplementedMsgServiceServer) ClearAccount(context.Context, *MsgClearAccount) (*MsgClearAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearAccount not implemented")
}
func (UnimplementedMsgServiceServer) ClearChain(context.Context, *MsgClearChain) (*MsgClearChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearChain not implemented")
}
func (UnimplementedMsgServiceServer) ClearToken(context.Context, *MsgClearToken) (*MsgClearTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearToken not implemented")
}
func (UnimplementedMsgServiceServer) DeletePortfolio(context.Context, *MsgDeletePortfolio) (*MsgDeletePortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePortfolio not implemented")
}
func (UnimplementedMsgServiceServer) DeleteAccount(context.Context, *MsgDeleteAccount) (*MsgDeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (UnimplementedMsgServiceServer) DeleteChain(context.Context, *MsgDeleteChain) (*MsgDeleteChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChain not implemented")
}
func (UnimplementedMsgServiceServer) DeleteToken(context.Context, *MsgDeleteToken) (*MsgDeleteTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteToken not implemented")
}
func (UnimplementedMsgServiceServer) DeleteLastAmount(context.Context, *MsgDeleteLastAmount) (*MsgDeleteLastAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLastAmount not implemented")
}
func (UnimplementedMsgServiceServer) mustEmbedUnimplementedMsgServiceServer() {}

// UnsafeMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServiceServer will
// result in compilation errors.
type UnsafeMsgServiceServer interface {
	mustEmbedUnimplementedMsgServiceServer()
}

func RegisterMsgServiceServer(s grpc.ServiceRegistrar, srv MsgServiceServer) {
	s.RegisterService(&MsgService_ServiceDesc, srv)
}

func _MsgService_CreatePortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePortfolio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreatePortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/CreatePortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreatePortfolio(ctx, req.(*MsgCreatePortfolio))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateAccount(ctx, req.(*MsgCreateAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/CreateChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateChain(ctx, req.(*MsgCreateChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/CreateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateToken(ctx, req.(*MsgCreateToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateAmount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/CreateAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateAmount(ctx, req.(*MsgCreateAmount))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_UpdatePortfolioName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePortfolioName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).UpdatePortfolioName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/UpdatePortfolioName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).UpdatePortfolioName(ctx, req.(*MsgUpdatePortfolioName))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_UpdateAccountName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAccountName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).UpdateAccountName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/UpdateAccountName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).UpdateAccountName(ctx, req.(*MsgUpdateAccountName))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_UpdateChainName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateChainName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).UpdateChainName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/UpdateChainName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).UpdateChainName(ctx, req.(*MsgUpdateChainName))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_UpdateTokenName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateTokenName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).UpdateTokenName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/UpdateTokenName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).UpdateTokenName(ctx, req.(*MsgUpdateTokenName))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_UpdateCoinGeckoId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCoinGeckoId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).UpdateCoinGeckoId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/UpdateCoinGeckoId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).UpdateCoinGeckoId(ctx, req.(*MsgUpdateCoinGeckoId))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/UpdateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).UpdateAddress(ctx, req.(*MsgUpdateAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ClearPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClearPortfolio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ClearPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/ClearPortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ClearPortfolio(ctx, req.(*MsgClearPortfolio))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ClearAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClearAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ClearAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/ClearAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ClearAccount(ctx, req.(*MsgClearAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ClearChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClearChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ClearChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/ClearChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ClearChain(ctx, req.(*MsgClearChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ClearToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClearToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ClearToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/ClearToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ClearToken(ctx, req.(*MsgClearToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_DeletePortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeletePortfolio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).DeletePortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/DeletePortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).DeletePortfolio(ctx, req.(*MsgDeletePortfolio))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).DeleteAccount(ctx, req.(*MsgDeleteAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_DeleteChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).DeleteChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/DeleteChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).DeleteChain(ctx, req.(*MsgDeleteChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_DeleteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).DeleteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/DeleteToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).DeleteToken(ctx, req.(*MsgDeleteToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_DeleteLastAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteLastAmount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).DeleteLastAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokt.keeper.MsgService/DeleteLastAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).DeleteLastAmount(ctx, req.(*MsgDeleteLastAmount))
	}
	return interceptor(ctx, in, info, handler)
}

// MsgService_ServiceDesc is the grpc.ServiceDesc for MsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pokt.keeper.MsgService",
	HandlerType: (*MsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePortfolio",
			Handler:    _MsgService_CreatePortfolio_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _MsgService_CreateAccount_Handler,
		},
		{
			MethodName: "CreateChain",
			Handler:    _MsgService_CreateChain_Handler,
		},
		{
			MethodName: "CreateToken",
			Handler:    _MsgService_CreateToken_Handler,
		},
		{
			MethodName: "CreateAmount",
			Handler:    _MsgService_CreateAmount_Handler,
		},
		{
			MethodName: "UpdatePortfolioName",
			Handler:    _MsgService_UpdatePortfolioName_Handler,
		},
		{
			MethodName: "UpdateAccountName",
			Handler:    _MsgService_UpdateAccountName_Handler,
		},
		{
			MethodName: "UpdateChainName",
			Handler:    _MsgService_UpdateChainName_Handler,
		},
		{
			MethodName: "UpdateTokenName",
			Handler:    _MsgService_UpdateTokenName_Handler,
		},
		{
			MethodName: "UpdateCoinGeckoId",
			Handler:    _MsgService_UpdateCoinGeckoId_Handler,
		},
		{
			MethodName: "UpdateAddress",
			Handler:    _MsgService_UpdateAddress_Handler,
		},
		{
			MethodName: "ClearPortfolio",
			Handler:    _MsgService_ClearPortfolio_Handler,
		},
		{
			MethodName: "ClearAccount",
			Handler:    _MsgService_ClearAccount_Handler,
		},
		{
			MethodName: "ClearChain",
			Handler:    _MsgService_ClearChain_Handler,
		},
		{
			MethodName: "ClearToken",
			Handler:    _MsgService_ClearToken_Handler,
		},
		{
			MethodName: "DeletePortfolio",
			Handler:    _MsgService_DeletePortfolio_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _MsgService_DeleteAccount_Handler,
		},
		{
			MethodName: "DeleteChain",
			Handler:    _MsgService_DeleteChain_Handler,
		},
		{
			MethodName: "DeleteToken",
			Handler:    _MsgService_DeleteToken_Handler,
		},
		{
			MethodName: "DeleteLastAmount",
			Handler:    _MsgService_DeleteLastAmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pokt/tx.proto",
}
