name: Portfolio

on: [pull_request, fork]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build

    - name: Run bash demo CRUD
      run: chmod -x ./.github/workflows/*.sh && bash ./.github/workflows/buildPortfolio.sh