# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Portfolio

on: [push, pull_request, fork]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    - uses: arduino/setup-protoc@v1.1.2
      with: 
        version: '3.x'

    - name: Install protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
  
    - name: Install protoc-gen-go-grpc 
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest && go mod tidy

    - name: Update PATH
      run: export PATH="$PATH:$(go env GOPATH)/bin"

    - name: Generate proto 
      run: bash ./run/buildProto.sh 

    - name: Build
      run: go build

    - name: Run bash
      run: go ./run/buildPortfolio.sh

    - name: Delete the token history for ATOM
      run: ./pokt deleteTokenHistory AccountName Cosmos-Hub ATOM 

    - name: Add a new token to Cosmos-Hub and then clear all the chain tokens' histories
      run: ./pokt addToken AccountName Cosmos-Hub USDC && ./pokt deleteChainHistory AccountName Cosmos-Hub 

    - name: Clear the Cosmos-Hub history
      run: ./pokt deleteChainHistory AccountName Cosmos-Hub

    - name: Clear AccountName History 
      run: ./pokt deleteAccountHistory AccountName 

    - name: Clear Portfolio History
      run: ./pokt deletePortfolioHistory 

    - name: Delete the token history for ATOM
      run: ./pokt deleteTokenHistory AccountName Cosmos-Hub ATOM 

    - name: Add a new amount and then clear the chain token history
      run: ./pokt addAmount AccountName Cosmos-Hub ATOM 10 && ./pokt deleteChainHistory AccountName Cosmos-Hub 

    - name: Remove Token named ATOM from Cosmos-Hub from Account named AccountName
      run: ./pokt removeToken AccountName Cosmos-Hub ATOM

    - name: Remove Chain named Cosmos-Hub from Account named AccountName 
      run: ./pokt removeChain AccountName Cosmos-Hub

    - name: Remove Account named AccountName 
      run: ./pokt removeAccount AccountName

  #    - name: Print All CoinGecko Coin Names, Ids and Symbols
  #      run: ./pokt printAllCoinIds