# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Portfolio

on: [push, pull_request, fork]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Print $ATOM price
      run: cd ./x/portfolio && go run main.go tokenPrice cosmos usd

    - name: Print All CoinGecko Coin Names, Ids and Symbols
      run: cd ./x/portfolio && go run main.go printAllCoinIds

    - name: Build PortfolioName Portfolio
      run: cd ./x/portfolio && go run main.go serve PortfolioName

    - name: Add Account AccountName to Portfolio
      run: cd ./x/portfolio && go run main.go addAccount AccountName

    - name: Remove Account named AccountName from Portfolio
      run: cd ./x/portfolio && go run main.go removeAccount AccountName

    - name: Add Chain named Cosmos-Hub to Account named AccountName
      run: cd ./x/portfolio && go run main.go addChain AccountName Cosmos-Hub Address 
