# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Portfolio

on: [push, pull_request, fork]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    - uses: arduino/setup-protoc@v1.1.2
      with: 
        version: '3.x'

    - name: Install protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
  
    - name: Install protoc-gen-go-grpc 
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest && go mod tidy

    - name: Update PATH
      run: export PATH="$PATH:$(go env GOPATH)/bin"

    - name: Give .sh permissions and Generate proto 
      run: chmod +x .github/workflows/*.sh && bash .github/workflows/buildProto.sh 

    - name: Build
      run: go build

    - name: Run bash demo CRUD
      run: bash .github/wokrflows/buildPortfolio.sh

  #    - name: Print All CoinGecko Coin Names, Ids and Symbols
  #      run: ./pokt printAllCoinIds